apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ2YWxheHkxOTk2Lmpmcm9nLmlvIjogewoJCQkiYXV0aCI6ICJkbWwyWld0bGVIUnlaVzFsUUdkdFlXbHNMbU52YlRwV1lXeGhlSGt4TWpNayIKCQl9Cgl9Cn0=

type: kubernetes.io/dockerconfigjson
